### PR TITLE
Add plugin for rewriting relative URIs to absolute URIs in image tags

### PR DESCRIPTION
**Pull request by kjeller**
This plugin implementation originates from dankito's Readability4JExtended. Rewritten to be more readable and with an included fix for handling of port in URI.

### CODE REVIEW

**Comment by kjeller** [comment]
~~Also, a thought about a future change. I would like to have the possability to use ArticleExtractor but also include image tags. But not entirely sure how to approach that. Having it as a separate plugin or modifying ArticleExtractor to be more modular?~~
I just saw an open issue that sounds like the problem I have been having. Will look into it myself when I got time.

**Comment by chimbori** [comment]
Thanks for the PR, including detailed tests!

Jsoup already has a handy way to get the absolute URI for any tag, using the `.attr("abs:href")` syntax. Is there something that that feature does not provide that makes this PR necessary?

(Probably better to discuss in an issue first)

Thanks!

**Comment by kjeller** [comment]
Thank you for the quick reply.

Great suggestion! I was not aware of that an absolute Uri attribute resolver was part of jsoup. Using that is more preferable.

Let me replace my parsing with that and I'll update this PR. I'm off traveling though it might take some time before I get to doing it

**Comment by kjeller** [comment]
In my latest commit I rewrote the absolute uri resolver to use jsoup absUrl and also made it more generic so it can be used for both img & anchor tags). It should also be easier to add more tags if needed.

**Comment by chimbori** [comment]
The basic question still remains unanswered,  Is there something that that feature does not provide that makes this PR necessary?

JSoup provides a clear way to get the absolute URL from any attribute, and current Crux users (including in our own apps) have been using that API to get the absolute URL whenever required with a simple change.

I don’t see any additional value this PR adds by replacing the tags in the tree. But it does add additional complexity and runtime processing costs, so if there’s something I am missing, please elaborate.

(In the future, it is usually best to discuss changes in an Issue before submitting a PR; having this discussion before the code was written would have been a better time.)

**Comment by kjeller** [comment]
It's necessary for applications (e.g. the  RSS reader Feeder) that on sync caches caches the extracted article in textually in HTML. The runtime processing cost here doesn't matter since it is on a schedule. Images are downloaded when a user issues a load / full fetch of article. We want to minimize the cost of fetching the article, resolving URIs and downloading images. If the URIs are already resolved then the user only needs to wait for downloading the images. (Of course the best way is to also download images while syncing, but this is somewhat dependent on the user setting "Image loading - only on wifi"). If you see another way of doing this please add an example and I can close this PR.

The background is that I am looking for a drop-in replacement for Readbility4J for the RSS reader app Feeder (https://github.com/spacecowboy/Feeder). Where Feeder utilizes Readbility4J to extract and parse articles where URIs are resolved in this way.

For future additions I will look into creating an issue first. Thanks for clarifying this.
Also, I understand that you want to keep the quality of additions and I'd suggest you consider adding this step to CONTRIBUTING.md since that is the guide I followed when adding this change.

**Comment by chimbori** [comment]
Oh this is very very interesting:

> looking for a drop-in replacement for Readbility4J for the RSS reader app Feeder 

I’m actually testing out Readability4J, and that parser appears to be much better than Crux (better stripping of useless content, retains `` tags everywhere in the doc, etc).

In my app (not in this library), I’ve been testing out Readability4J accessed as a Crux plugin. My eventual plan is to remove the HTML-parsing specific code from Crux, make it into a library for unfurling, and add a dependency on Readability4J to maintain compatibility.

> The runtime processing cost here doesn't matter since it is on a schedule.

Not all use cases of this library involve a background task, and even then, local CPU usage is still the same for work that is  avoidable.

> We want to minimize the cost of fetching the article, resolving URIs and downloading images. If the URIs are already resolved then the user only needs to wait for downloading the images.

Why is it not possible to modify the fetching code to read the attribute `abs:src` instead of `src`? It’s such a tiny change, and is the more widely supported way of doing this.

I don’t think this PR should proceed, now that you’ve explained the core problem you’re trying to solve, and given the roadmap I just shared.

**Comment by kjeller** [comment]
Ah okay I misunderstood what you meant. Yes, modifying the fetching code would make this change unnecessary and would also avoid wasting cycles on work that could be avoided. 

> I don’t think this PR should proceed, now that you’ve explained the core problem you’re trying to solve, and given the roadmap I just shared.

Agreed, let's close this.

**Pull request closed without merging**
