### PR TITLE
add some missing properties

### PR DESCRIPTION
**Pull request by sigpwned**
This gets the maven pom building. I'll make some further updates to get it ready for maven central!

### CODE REVIEW

**Comment by chimbori** [comment]
Hey, just to clarify, I’m supposed to wait for you to push more commits to this PR before merging it, correct?

**Comment by sigpwned** [comment]
Yes! Sorry for the radio silence. Work picked up -- I will be able to get this ready for maven this weekend. Does that time frame work for you?

**Comment by chimbori** [comment]
Absolutely! No hurry from me. I wanted to make sure we weren’t waiting on each other for the next step.

**Comment by chimbori** [comment]
This is obsolete. Publishing to Maven Central via Gradle has been set up, and it directly reads from `build.gradle` so a separate `pom.xml` need not be maintained.

**Pull request closed without merging**
